apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  SPRING_APPLICATION_NAME: {{ .Values.config.springApplicationName | quote }}
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
